name: Python CI with Poetry

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write      # Ensure we can push to gh-pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install

      - name: Generate Proto Files
        run: poetry run generate-grpc

      - name: Run Tests
        run: |
          mkdir -p reports/allure-results
          poetry run pytest --alluredir=reports/allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Generate Allure report
        run: |
          allure generate reports/allure-results -o reports/allure-report --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/allure-report
